# For Intermediate

Inspecting and summarizing the proteomics data.


```{r}
library(readr)
library(plotly)
library(tidyverse)
```

Inspecting and summarizing the proteomics data.

<div class="remember">
  <strong>📌 Remember:</strong> Load the library before starting the analysis.
</div>

**Load and prepare the data**
 
`read_csv` = reads a csv file

``` {r, echo=TRUE}
data <- read_csv("../data-01/PXD040621_peptides.csv", show_col_types = FALSE)
```

<div class="remember">
  <strong>📌 Remember:</strong> Remember: You can use the `DT` package to visualize the data.
</div>

```{r}
DT::datatable(
  data = head(data, 1000),  # show only the first 1000 rows
  rownames = FALSE,
  extensions = c('Buttons', 'Scroller'),
  options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv'),
    deferRender = TRUE,
    scrollX = TRUE,
    scrollY = 200,
    scroller = TRUE
  ),
  caption = 'proteomics metadata'
)
```

```{r}
protein_data_parsed_mut <- readRDS("../data-01/protein_data_parsed_mut.rds")

```


```{r}

plot_ly(
  data = protein_data_parsed_mut,
  x = ~Intensity,
  color = ~Reference,        # equivalent to fill in ggplot2
  type = "histogram"
) %>%
  layout(
    barmode = "stack", # "overlay" or "stack"
    title = "Protein Intensity Distribution by Label",
    xaxis = list(title = "Intensity"),
    yaxis = list(title = "Count")
  )

```


